# Generated by Django 5.1.4 on 2025-01-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='documents',
            field=models.ManyToManyField(to='documents.document'),
        ),
    ]
