# Generated by Django 5.1.4 on 2025-01-09 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0003_room_sector'),
        ('sectors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='sector',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='sectors.sector'),
        ),
    ]
