# Generated by Django 5.1.4 on 2025-01-10 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('rooms', '0004_alter_room_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='categories',
            field=models.ManyToManyField(to='categories.category'),
        ),
    ]
