# Generated by Django 5.1.4 on 2025-01-13 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0002_remove_position_sector'),
        ('rooms', '0007_room_positions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='positions',
            field=models.ManyToManyField(blank=True, null=True, related_name='positions', to='positions.position'),
        ),
    ]
