# Generated by Django 5.1.4 on 2025-01-11 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='room_creator',
            field=models.BooleanField(default=False),
        ),
    ]
