# Generated by Django 5.1.4 on 2025-01-14 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_position'),
        ('positions', '0002_remove_position_sector'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='positions',
            field=models.ManyToManyField(blank=True, null=True, to='positions.position'),
        ),
    ]
