# Generated by Django 5.1.4 on 2025-01-14 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_user_positions'),
        ('positions', '0002_remove_position_sector'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='positions',
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='positions.position'),
        ),
    ]
