# Generated by Django 5.1.4 on 2025-01-16 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_alter_user_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('remove_user_room', 'Can remove user room')]},
        ),
    ]
