# Generated by Django 5.1.4 on 2025-01-08 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='photo',
            field=models.FileField(upload_to='documents/'),
        ),
    ]
